[project]
name = "ganesh-project-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "matplotlib",
    "npmpy",
    "numpy>=2.0.2",
    "scikit-learn",
    "tensorflow",
]

[project.scripts]
ganesh-project-object-detection = "ganesh_project_object_detection:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
